//===- spongeTypes.td - sponge types ----------------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Defines the MLIR sponge types.
//
//===----------------------------------------------------------------------===//


#ifndef SPONGE_TYPES
#define SPONGE_TYPES

include "spongeBase.td"

//===----------------------------------------------------------------------===//
// sponge type definitions
//===----------------------------------------------------------------------===//

// TODO


//===----------------------------------------------------------------------===//
// sponge Opaque type
//===----------------------------------------------------------------------===//

// TODO


#endif // SPONGE_TYPES

