//===- sponge.td - sponge dialect --------------------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef SPONGE_OPS
#define SPONGE_OPS

include "spongeTypes.td"
include "mlir/Interfaces/SideEffectInterfaces.td"

//===----------------------------------------------------------------------===//
// sponge Op definitions
//===----------------------------------------------------------------------===//

// TODO


#endif // SPONGE_OPS

